table 2023
	lineageTag: 8afc8963-86b4-40e2-ae31-e6ac09457686

	column Incident_id
		dataType: string
		lineageTag: 83995408-8db0-4805-aa76-8f03b8c9aef3
		summarizeBy: none
		sourceColumn: Incident_id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 705ff213-6337-4c7e-9186-32f2e4433826
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 371b610f-8ffd-46c2-85c9-38689d6897ba
			defaultHierarchy: LocalDateTable_fac32359-89b4-49e3-ac8c-aa60b137c26b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 44477e4a-7578-4179-8068-b0e70c993ae8
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Day
		dataType: string
		lineageTag: b6f2e925-cbe8-4f26-b4be-53b2812912fb
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Station
		dataType: string
		lineageTag: 5cca357e-0475-47c6-8b46-0f05d6bc10ca
		summarizeBy: none
		sourceColumn: Station

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: 5751a4a2-00fd-45fa-bbca-9dab33ca89fd
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column 'Min Delay'
		dataType: int64
		formatString: 0
		lineageTag: aed85591-9979-4bfd-b4fa-377090ecf71a
		summarizeBy: sum
		sourceColumn: Min Delay

		annotation SummarizationSetBy = Automatic

	column 'Min Gap'
		dataType: int64
		formatString: 0
		lineageTag: 1c401702-95c2-47d4-8966-899a37548712
		summarizeBy: sum
		sourceColumn: Min Gap

		annotation SummarizationSetBy = Automatic

	column Bound
		dataType: string
		lineageTag: 4f1353d3-d353-4669-8f4b-1327cfd8df1f
		summarizeBy: none
		sourceColumn: Bound

		annotation SummarizationSetBy = Automatic

	column Line
		dataType: string
		lineageTag: 7ff8d501-e5c4-42bb-9333-4c6dd0149088
		summarizeBy: none
		sourceColumn: Line

		annotation SummarizationSetBy = Automatic

	column Vehicle
		dataType: int64
		formatString: 0
		lineageTag: afa92a09-a30d-4cfe-a130-fafcadda70af
		summarizeBy: sum
		sourceColumn: Vehicle

		annotation SummarizationSetBy = Automatic

	partition 2023 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(ProjectFolder & "assets\ttc-subway-delay-data-2023.xlsx"), null, true),
				    #"2023_Sheet" = Source{[Item="2023",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"2023_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Time", type time}, {"Day", type text}, {"Station", type text}, {"Code", type text}, {"Min Delay", Int64.Type}, {"Min Gap", Int64.Type}, {"Bound", type text}, {"Line", type text}, {"Vehicle", Int64.Type}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Added Index", "Incident_id", each "2023" & "-" & Text.From([Index])),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"Incident_id", "Date", "Time", "Day", "Station", "Code", "Min Delay", "Min Gap", "Bound", "Line", "Vehicle", "Index"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Index"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

